[platformio]
default_envs = car

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

lib_deps =
    h2zero/NimBLE-Arduino@^2.5.0
    

;========================
; Car (ESP32-S3, Access ECU)
;========================
[env:car]
board = esp32-s3-devkitc-1
upload_port = COM10
monitor_port = COM10
monitor_filters = log2file, default
build_flags =
    -D IS_CAR=1
    -D UWB_USE_MOCK=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

build_src_filter =
    +<shared/>
    +<os/>
    +<crypto/>
    +<protocol/>
    +<uwb/>
    +<car/>
    +<can/>
    +<nfc/>
    -<keyfob/>
    -<gateway/>
    -<uart/>

lib_deps =
    ${env.lib_deps}
    miguelbalboa/MFRC522@^1.4.8
;========================
; Keyfob (ESP32-C3)
;========================
[env:keyfob]
board = esp32-c3-devkitm-1
upload_port = COM9
monitor_port = COM9
build_flags = 
    -D IS_KEYFOB=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    ${env.lib_deps}
    bblanchon/ArduinoJson@^7.0.0

build_src_filter =
    +<shared/>
    +<os/>
    +<crypto/>
    +<protocol/>
    +<keyfob/>
    -<can/>
    -<car/>
    -<gateway/>
    

;========================
; Gateway (ESP32-S3, YoloUNO)
;========================
[env:gateway]
board = esp32-s3-devkitc-1
upload_port = COM8
monitor_port = COM8
build_flags =
    -D IS_GATEWAY=1

lib_deps =
    ${env.lib_deps}
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.4.17
    bblanchon/ArduinoJson@^7.0.0

build_src_filter =
    +<shared/>
    +<os/>
    +<cloud/>
    +<gateway/>
    +<can/>
    -<uart/>
    -<car/>
    -<keyfob/>
    