; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = car

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps = 
	h2zero/NimBLE-Arduino@^2.5.0

[env:car]
board = esp32-s3-devkitc-1
upload_port = COM8
monitor_port = COM8
monitor_filters = log2file, default
build_flags = 
	-D IS_CAR=1
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = 
	+<shared/>
	+<os/>
	+<crypto/>
	+<protocol/>
	+<uwb/>
	-<uwb/uwb_mock.cpp>
	+<car/>
	+<can/>
	+<nfc/>
	+<lcd/>
	-<keyfob/>
	-<gateway/>
	-<uart/>
lib_deps =
	${env.lib_deps}
	miguelbalboa/MFRC522@^1.4.8
	rweather/Crypto@^0.4.0
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
platform_packages = platformio/tool-scons@^4.41101.0

; Bring-up LCD 1602 I2C độc lập (Hello World) - nạp vào board car, không BLE/UWB/CAN
[env:lcd_test]
board = esp32-s3-devkitc-1
upload_port = COM8
monitor_port = COM8
build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter =
	+<lcd_test/>
lib_deps =
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
platform_packages = platformio/tool-scons@^4.41101.0

[env:keyfob]
board = esp32-s3-devkitc-1
upload_port = COM15
monitor_port = COM15
build_flags = 
	-D IS_KEYFOB=1
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	${env.lib_deps}
	bblanchon/ArduinoJson@^7.0.0
	rweather/Crypto@^0.4.0
build_src_filter = 
	+<shared/>
	+<os/>
	+<crypto/>
	+<protocol/>
	+<keyfob/>
	-<can/>
	-<car/>
	-<gateway/>
platform_packages = platformio/tool-scons@^4.41101.0

[env:gateway]
board = esp32-s3-devkitc-1
upload_port = COM9
monitor_port = COM9
build_flags = 
	-D IS_GATEWAY=1
lib_deps = 
	${env.lib_deps}
	mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.4.17
	bblanchon/ArduinoJson@^7.0.0
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
build_src_filter =
	+<shared/>
	+<os/>
	+<cloud/>
	+<gateway/>
	+<can/>
	+<lcd/>
	-<uart/>
	-<car/>
	-<keyfob/>
platform_packages = platformio/tool-scons@^4.41101.0
